name: Packer GHA

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
      - master
    paths: 
      - 'hippo-image.pkr.hcl'

  push:
    branches: 
      - main
      - master
    paths: 
      - 'hippo-image.pkr.hcl'      

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Run PACKER container, build and deploy
      uses: docker://hashicorp/packer:light
      env: 
        AWS_ACCESS_KEY: ${{ secrets.PACKER_AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.PACKER_AWS_ACCESS_KEY }}
      with:
        args: "build hippo-image.pkr.hcl"
